[package]
name = "yum-blackjack"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.30"
lazy_static = "1.5.0"
macroquad = "0.4.13"
rand = "0.8.5"
tokio = { version = "1.40.0", features = ["full"] }
